coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%

flags:
  domain:
    paths:
      - domain/src/main/
    carryforward: true
  data:
    paths:
      - data/src/main/
    carryforward: true
  app:
    paths:
      - app/src/main/
    carryforward: true

comment:
  layout: "reach,diff,flags"
  behavior: default
